version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /app
      - gem_cache:/usr/local/bundle
volumes:
  gem_cache: